DELIMITER $$

DROP PROCEDURE IF EXISTS sp_getAllCourseDetails $$

CREATE DEFINER=`CSCI5308_22_DEVINT_USER`@`%` PROCEDURE DELIMITER $$
CREATE DEFINER=`CSCI5308_22_TEST_USER`@`%` PROCEDURE `sp_getAllCourseDetails`()
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT *
	FROM course;

	COMMIT;
END $$;
DELIMITER ;